version: "3"
services:
    portainer:
        image: "portainer/portainer"
        ports:
            - "80:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: "always"